version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  python:
    build: .
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    depends_on:
      - redis
    tty: true
    stdin_open: true
    environment:
      - REDIS_HOST=redis